os: osx
osx_image: xcode9
language: swift
xcode_workspace: SocialMessenger.xcworkspace
xcode_scheme: SocialMessengerTests

cache: cocoapods

before_install:
  - gem install cocoapods -v '1.3.1'
  - pod repo update