os: osx
osx_image: xcode9
language: swift
xcode_workspace: SocialMessenger.xcworkspace # path to your xcodeproj folder
xcode_scheme: SocialMessenger

cache: cocoapods

before_install:
  - gem install cocoapods -v '1.3.1'
  - pod update