os: osx
osx_image: xcode9
language: swift
xcode_workspace: SocialMessenger.xcworkspace
xcode_scheme: SocialMessengerTests

cache: cocoapods

before_install:
  - bundle install
  - bundle exec pod repo update

install:
  - bundle exec pod install

script:
  - bundle exec fastlane test